# Generated by Django 4.2 on 2024-08-02 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribe',
            new_name='Subscribe',
        ),
    ]
