# Generated by Django 4.2 on 2024-08-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_subcribe_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
