# Generated by Django 4.2 on 2024-08-29 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_rename_email_comment_email_rename_name_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
